services:
  livekit:
    image: livekit/livekit-server:v1.6.4
    container_name: livekit
    restart: unless-stopped
    ports:
      - "7880:7880"
      - "7881:7881"
      - "50000-60000:50000-60000/udp"
    # networks:
    #  - weengoo-net
    depends_on:
      redis:
        condition: service_healthy
    entrypoint: ["/bin/bash", "-c", "./wait-for-redis.sh && livekit-server --config /etc/livekit.yaml"]
    volumes:
      - ./livekit.yaml:/etc/livekit.yaml
      - ./wait-for-redis.sh:/wait-for-redis.sh
    network_mode: "service:redis"

networks:
  weengoo-net:
    external: true
